In [11]:
import numpy as np
import torch as tr

In [ ]:
vctr = np.array([[1,47,354]])
print(vctr)

[[  1  47 354]]
 


(None, None)

Use "np.transpose(vector)" to transpose

In [ ]:
transpose_vctr = np.transpose(vctr)
print(transpose_vctr)

[[  1]
 [ 47]
 [354]]
 


(None, None)

Use ".T" to transpose

In [8]:
transpose_vctr = vctr.T
print(transpose_vctr), print(' ')

[[  1]
 [ 47]
 [354]]
 


(None, None)

Transposing for a Matrix

In [ ]:
matrx = np.array([[1,64,78,943],[74,35,59,37],[33,17,978,41]])
print(matrx)

[[  1  64  78 943]
 [ 74  35  59  37]
 [ 33  17 978  41]]


In [10]:
# transpose_mtrx = np.transpose(matrx)
transpose_mtrx = matrx.T

print(transpose_mtrx)

[[  1  74  33]
 [ 64  35  17]
 [ 78  59 978]
 [943  37  41]]


Transpose using PyTorch (vector & matrix)

In [12]:
tnsr_1d = tr.tensor([[1,64,78,943]])
tnsr_2d = tr.tensor([[1,64,78,943],[74,35,59,37],[33,17,978,41]])

trnsps_1d = tnsr_1d.T
trnsps_2d = tnsr_2d.T

In [13]:
print(trnsps_1d)
print(trnsps_2d)

tensor([[  1],
        [ 64],
        [ 78],
        [943]])
tensor([[  1,  74,  33],
        [ 64,  35,  17],
        [ 78,  59, 978],
        [943,  37,  41]])


lets examine the dataTypes

In [15]:
print("The data type of vctr is:", type(vctr))
print("The data type of matrx is:", type(matrx))
print("The data type of tnsr_1d is:", type(tnsr_1d))
print("The data type of tnsr_2d is:", type(tnsr_2d))

The data type of vctr is: <class 'numpy.ndarray'>
The data type of matrx is: <class 'numpy.ndarray'>
The data type of tnsr_1d is: <class 'torch.Tensor'>
The data type of tnsr_2d is: <class 'torch.Tensor'>
