In [29]:
import numpy as np
import torch 

In [30]:
np.random.randn(5)

array([-0.65141987, -1.77546915,  0.23428583,  1.23939986, -0.65033427])

In [31]:
np.random.seed(28)

print(np.random.randn(6))
print(np.random.randn(6))
# Rerunning this block will produce the same 6 numbers in each rows

[ 0.44633238  1.66912005 -0.26427996 -0.96783493  0.05918843  1.51461999]
[ 0.33687044 -0.3023687  -0.8386418  -0.51773125  0.25350786 -2.48470399]


### New seed mechanism in numpy

In [32]:
randomseed1 = np.random.RandomState(17)
randonseed2 = np.random.RandomState(48532)
print("First line for randomseed1: ", randomseed1.randn(5))
print("First line for randomseed2: ",randonseed2.randn(5))
print("Second line for randomseed1: ", randomseed1.randn(5))
print("Second line for randomseed2: ",randonseed2.randn(5))


# Rerunning this block will produce the same 5 numbers in each rows

First line for randomseed1:  [ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
First line for randomseed2:  [-2.40526347  0.77966358 -1.2598188   1.81978196 -0.55698952]
Second line for randomseed1:  [ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
Second line for randomseed2:  [ 0.42118634 -0.22050729  0.56480075  0.13975136  1.86741644]


## Using PyTorch

In [33]:
torch.randn(5)

tensor([-0.6124, -1.1835, -1.4831,  1.8004,  0.0096])

In [34]:
torch.manual_seed(17)
torch.randn(5)


# Rerunning this block will produce the same 5 numbers

tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])

PyTorch's "manual_seed" dont affect the numpy's random seed