In [1]:
import numpy as np
import torch
import torch.nn as nn

In [ ]:
vect = np.array([1,40,2,-3])

max_val = np.max(vect)
min_val = np.min(vect)

arg_min = np.argmin(vect)
arg_max = np.argmax(vect)


In [3]:
print(f"Max Value: {max_val}, Min value: {min_val}")
print(f"ArgMax Value: {arg_max}, ArgMin value: {arg_min}")

Max Value: 40, Min value: -3
ArgMax Value: 1, ArgMin value: 3


### With MAtrix

In [4]:
M = np.array([
   [0,1,10],
   [20,8,5] 
])

print(M)

[[ 0  1 10]
 [20  8  5]]


In [ ]:
minval1 = np.min(M) # Entire matrix min
minval2 = np.min(M, axis=0) # minimum values across rows (for each column)
minval3 = np.min(M, axis=1) # minimum values across columns (for each row)


In [ ]:
print(minval1)
print(minval2) # columns 
print(minval3) # rows

0
[0 1 5]
[0 5]


In [ ]:
argmin1 = np.argmin(M)
argmin2 = np.argmin(M, axis=0) # index of the minimum values across rows (for each column)
argmin3 = np.argmin(M, axis=1) # index of the minimum values across columns (for each row)


In [ ]:
print(argmin1)
print(argmin2) # column 
print(argmin3) # row

0
[0 0 1]
[0 2]


### USing PyTorch

In [ ]:
tsr = torch.Tensor([
    [0,1,10],
    [20,8,5] 
])
print(tsr)