In [1]:
import numpy as np
import torch as tr

Genrating Random array of given dimension

In [12]:
r1 = np.random.randn(3,4)
r2 = np.random.randn(4,5)
r3 = np.random.randn(5,7)
r4 = np.random.randn(5,4)

In [13]:
rounded_result1 = np.round(np.matmul(r1,r2),3)
print(rounded_result1)

[[-0.836 -2.384  4.197 -0.057  2.714]
 [-0.49   0.776 -1.294 -0.269  0.11 ]
 [ 0.115  0.441  2.788 -1.663  1.357]]


In [14]:
rounded_result2 = np.round(np.matmul(r1,r3),3)
print(rounded_result2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 4)

In [15]:
rounded_result3 = np.round(np.matmul(r2,r3),2)
print(rounded_result3)

[[ 0.04  1.66 -1.23 -2.24  0.31  0.12 -0.01]
 [ 5.01  0.03 -3.6   2.22 -6.11 -1.3  -0.38]
 [-2.51  0.6  -0.23  1.6   1.33 -0.88  0.13]
 [ 0.21 -0.03 -0.42 -0.24 -0.49  0.49  1.2 ]]


In [17]:
rounded_result5 = np.round(r1@r4,2)
print(rounded_result5)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 4)

In [16]:
rounded_result4 = np.round(r1@r4.T,2)
print(rounded_result4)

[[-1.26  2.28  0.9   0.66 -0.92]
 [ 1.   -1.38 -0.73 -0.93 -0.38]
 [ 0.81 -0.14  0.7   5.05  1.74]]
